[package]
name = "owner/src"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
TestEZ = "roblox/testez@0.4.1"
Promise = "evaera/promise@4.0.0"
Charm = "littensy/charm@0.10.0"
Signal = "sleitnick/signal@2.0.3"
Component = "sleitnick/component@2.4.8"
